_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 13
                - 23
                - 55
                - 62
            "4": 3.12.2
            "5": 0.18.1
            "8":
                - 1
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.1
            "13": darwin-arm64
