_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 7
                - 16
                - 23
                - 38
                - 55
            "4": 3.12.2
            "5": 0.18.1
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": darwin-arm64
layers:
    value: 64
